# air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main main.go"
  bin = "tmp/main"
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  delay = 1000
  log = "air.log"
  send_interrupt = true
  kill_delay = "2s"

[log]
  color = "true"
  time = "true"
